AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ConnecTraEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: ami-0abcdef1234567890
      SecurityGroupIds: [!Ref ConnecTraSG]
      UserData: !Base64 |
        #!/bin/bash
        yum install -y docker nodejs
        docker run -p 3000:3000 connec-tra:latest
